In [53]:
import os
os.chdir('/Users/davisjohnson/Downloads')

In [182]:
import pandas as pd
import numpy as np
nba_2017_2018 = pd.read_csv('archive-2/NBA Players Stats 201718.csv')

In [183]:
nba_2017_2018 = nba_2017_2018.drop(columns=['Rk','Tm', 'Pos'], axis=1)
nba_2017_2018['Player'] = nba_2017_2018['Player'].str.split('\\').str[0]
nba_2017_2018.fillna(0, inplace=True)

In [184]:
cols_to_keep = ['Player', 'Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
                '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
                'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']

# Group the data by player and calculate the weighted average and sum of the other columns
nba_2017_2018 = nba_2017_2018.groupby(['Player', 'Age'])[cols_to_keep].agg({'G': 'sum', 'GS': 'sum', 
                                                                                     'MP': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     'FG': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     'FGA': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     'FG%': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     '3P': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     '3PA': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     '3P%': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     '2P': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     '2PA': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     '2P%': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     'eFG%': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     'FT': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     'FTA': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     'FT%': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     'ORB': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     'DRB': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     'TRB': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     'AST': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']), 
                                                                                     'STL': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']),
                                                                                     'BLK': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']),
                                                                                     'TOV': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']),
                                                                                     'PF': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G']),
                                                                                     'PTS': lambda x: np.average(x, weights=nba_2017_2018.loc[x.index, 'G'])}).reset_index()

In [185]:
nba_2017_2018

,Player,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Aaron Brooks,33,32,1,5.900000,0.9,2.200000,0.406000,0.3,1.0,...,0.7270,0.2,0.300000,0.500000,0.600000,0.200000,0.000000,0.300000,0.900000,2.300000
1,Aaron Gordon,22,58,57,32.900000,6.5,14.900000,0.434000,2.0,5.9,...,0.6980,1.5,6.400000,7.900000,2.300000,1.000000,0.800000,1.800000,1.900000,17.600000
2,Aaron Harrison,23,9,3,25.900000,2.1,7.700000,0.275000,1.0,4.8,...,0.7650,0.4,2.200000,2.700000,1.200000,1.000000,0.200000,0.300000,3.000000,6.700000
3,Aaron Jackson,31,1,0,35.000000,3.0,9.000000,0.333000,1.0,4.0,...,0.5000,2.0,1.000000,3.000000,1.000000,0.000000,0.000000,1.000000,4.000000,8.000000
4,Abdel Nader,24,48,1,10.900000,1.0,3.100000,0.336000,0.5,1.4,...,0.5900,0.3,1.200000,1.500000,0.500000,0.300000,0.200000,0.700000,0.900000,3.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,Zach Randolph,36,59,57,25.600000,6.1,12.900000,0.473000,0.9,2.5,...,0.7850,1.6,5.100000,6.700000,2.200000,0.700000,0.200000,2.000000,2.000000,14.500000
536,Zaza Pachulia,33,69,57,14.100000,2.2,3.800000,0.564000,0.0,0.0,...,0.8060,1.3,3.400000,4.700000,1.600000,0.600000,0.200000,1.000000,1.800000,5.400000
537,Zhou Qi,22,18,0,6.900000,0.3,1.800000,0.188000,0.1,1.1,...,0.6670,0.3,0.900000,1.200000,0.100000,0.100000,0.800000,0.600000,0.800000,1.200000
538,Álex Abrines,24,75,8,15.100000,1.5,3.900000,0.395000,1.1,2.9,...,0.8480,0.3,1.200000,1.500000,0.400000,0.500000,0.100000,0.300000,1.700000,4.700000
539,Ömer Aşık,31,36,0,10.094444,0.5,1.194444,0.411833,0.0,0.0,...,0.2835,0.5,2.088889,2.588889,0.172222,0.122222,0.194444,0.516667,1.105556,1.216667

In [186]:
nba_2017_2018 = nba_2017_2018.round(2)
nba_2017_2018

,Player,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Aaron Brooks,33,32,1,5.90,0.9,2.20,0.41,0.3,1.0,...,0.73,0.2,0.30,0.50,0.60,0.20,0.00,0.30,0.90,2.30
1,Aaron Gordon,22,58,57,32.90,6.5,14.90,0.43,2.0,5.9,...,0.70,1.5,6.40,7.90,2.30,1.00,0.80,1.80,1.90,17.60
2,Aaron Harrison,23,9,3,25.90,2.1,7.70,0.28,1.0,4.8,...,0.76,0.4,2.20,2.70,1.20,1.00,0.20,0.30,3.00,6.70
3,Aaron Jackson,31,1,0,35.00,3.0,9.00,0.33,1.0,4.0,...,0.50,2.0,1.00,3.00,1.00,0.00,0.00,1.00,4.00,8.00
4,Abdel Nader,24,48,1,10.90,1.0,3.10,0.34,0.5,1.4,...,0.59,0.3,1.20,1.50,0.50,0.30,0.20,0.70,0.90,3.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,Zach Randolph,36,59,57,25.60,6.1,12.90,0.47,0.9,2.5,...,0.78,1.6,5.10,6.70,2.20,0.70,0.20,2.00,2.00,14.50
536,Zaza Pachulia,33,69,57,14.10,2.2,3.80,0.56,0.0,0.0,...,0.81,1.3,3.40,4.70,1.60,0.60,0.20,1.00,1.80,5.40
537,Zhou Qi,22,18,0,6.90,0.3,1.80,0.19,0.1,1.1,...,0.67,0.3,0.90,1.20,0.10,0.10,0.80,0.60,0.80,1.20
538,Álex Abrines,24,75,8,15.10,1.5,3.90,0.40,1.1,2.9,...,0.85,0.3,1.20,1.50,0.40,0.50,0.10,0.30,1.70,4.70
539,Ömer Aşık,31,36,0,10.09,0.5,1.19,0.41,0.0,0.0,...,0.28,0.5,2.09,2.59,0.17,0.12,0.19,0.52,1.11,1.22

In [187]:
all_star_list = ['Kemba Walker', 'Kyrie Irving', 'Kawhi Leonard', 'Giannis Antetokounmpo', 
                'Joel Embiid', 'Kyle Lowry', 'Victor Oladipo', 'Khris Middleton', 'Bradley Beal',
                'Ben Simmons', 'Blake Griffin', 'Nikola Vučević', "D'Angelo Russell",
                'Stephen Curry', 'James Harden', 'Kevin Durant', 'Paul George', 'LeBron James',
                'Russell Westbrook', 'Damian Lillard', 'Klay Thompson', 'Anthony Davis', 
                'LaMarcus Aldridge', 'DeMarcus Cousins', 'Nikola Jokić', 'Karl-Anthony Towns']
nba_2017_2018['AS_NY'] = nba_2017_2018['Player'].apply(lambda x: 1 if x in all_star_list else 0)

In [188]:
nba_2018_2019 = pd.read_csv('archive-2/NBA Players Stats 201819.csv')

In [189]:
nba_2018_2019 = nba_2018_2019.drop(columns=['Rk','Tm','Pos'], axis=1)
nba_2018_2019['Player'] = nba_2018_2019['Player'].str.split('\\').str[0]
nba_2018_2019.fillna(0, inplace=True)

In [190]:
cols_to_keep = ['Player', 'Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
                '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
                'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS']

# Group the data by player and calculate the weighted average and sum of the other columns
nba_2018_2019 = nba_2018_2019.groupby(['Player', 'Age'])[cols_to_keep].agg({'G': 'sum', 'GS': 'sum', 
                                                                                     'MP': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     'FG': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     'FGA': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     'FG%': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     '3P': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     '3PA': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     '3P%': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     '2P': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     '2PA': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     '2P%': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     'eFG%': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     'FT': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     'FTA': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     'FT%': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     'ORB': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     'DRB': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     'TRB': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     'AST': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']), 
                                                                                     'STL': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']),
                                                                                     'BLK': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']),
                                                                                     'TOV': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']),
                                                                                     'PF': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G']),
                                                                                     'PTS': lambda x: np.average(x, weights=nba_2018_2019.loc[x.index, 'G'])}).reset_index()

In [191]:
nba_2018_2019 = nba_2018_2019.round(2)

In [192]:
all_star_list = ['Kemba Walker', 'Trae Young', 'Giannis Antetokounmpo', 'Pascal Siakam', 'Joel Embiid',
                'Kyle Lowry', 'Ben Simmons', 'Jimmy Butler', 'Khris Middleton', 'Bam Adebayo', 
                'Jayson Tatum', 'Domantas Sabonis', 'James Harden', 'Luka Dončić', 'LeBron James',
                'Kawhi Leonard', 'Anthony Davis', 'Chris Paul', 'Russell Westbrook', 'Damian Lillard', 
                'Donovan Mitchell', 'Brandon Ingram', 'Nikola Jokić', 'Rudy Gobert', 'Devin Booker']
nba_2018_2019['AS_NY'] = nba_2018_2019['Player'].apply(lambda x: 1 if x in all_star_list else 0)

In [193]:
duplicated_players = nba_2017_2018[nba_2017_2018.duplicated(subset='Player', keep=False)]['Player'].tolist()

# Select rows with duplicated player names
duplicated_rows = nba_2017_2018[nba_2017_2018['Player'].isin(duplicated_players)]

duplicated_rows

Empty DataFrame
Columns: [Player, Age, G, GS, MP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, AS_NY]
Index: []

[0 rows x 28 columns]

In [194]:
duplicated_players = nba_2018_2019[nba_2018_2019.duplicated(subset='Player', keep=False)]['Player'].tolist()

# Select rows with duplicated player names
duplicated_rows = nba_2018_2019[nba_2018_2019['Player'].isin(duplicated_players)]

duplicated_rows

Empty DataFrame
Columns: [Player, Age, G, GS, MP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, AS_NY]
Index: []

[0 rows x 28 columns]

In [196]:
nba_2017_2018_subset = nba_2017_2018[nba_2017_2018['G'] < 84]

nba_2017_2018_subset['AS_NY'].value_counts()

0    482
1     25
Name: AS_NY, dtype: int64

In [197]:
nba_2018_2019_subset = nba_2018_2019[nba_2018_2019['G'] < 84]

nba_2018_2019_subset['AS_NY'].value_counts()

0    448
1     24
Name: AS_NY, dtype: int64

In [202]:
nba_2018_2019.columns

Index(['Player', 'Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA',
       '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB',
       'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'AS_NY'],
      dtype='object')